apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: company-projects
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
spec:
  # Source of the application manifests
  source:
    path: src/app-of-apps/overlays/local