apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
    - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.3.6

resources:
    - ./resources/argo-cd-app.yaml
    - ./resources/argo-cd-proj.yaml
    - ./resources/github-secret-sealed.json

patchesStrategicMerge:
    - ./resources/argo-cd-cm.yaml