apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: company-projects
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
spec:
  # The project the application belongs to.
  project: argocd-project

  # Source of the application manifests
  source:
    repoURL: git@github.com:Gatefail/argocd-applications.git
    targetRevision: HEAD
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    manual:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

  # Ignore differences at the specified json pointers
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas