apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
    environment: local
      
resources:
    - ../../base

patchesStrategicMerge:
    - ./argo-cd-app.yaml
    - ./monitoring-projects-path.yaml
    - ./company-projects-app.yaml