apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
    - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.3.6

resources:
    - github-secret-sealed.json
    - project-alpha-ns.yaml
    - applications/some-first-app.yaml
