apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  statusbadge.enabled: 'true'
  users.anonymous.enabled: "true"
  repositories: |
    - url: git@github.com:Gatefail/argocd-setup.git

  repository.credentials: |
    - url: git@github.com:Gatefail
      sshPrivateKeySecret:
        name: github-secret
        key: github_personal
