apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-project
  namespace: argocd
spec:
  description: Argocd-Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'git@github.com:Gatefail/argocd-setup.git'
  - 'git@github.com:Gatefail/argocd-applications.git'
  - 'git@github.com:Gatefail/argocd-monitoring.git'
  # Only permit applications to deploy to the argocd namespace in the same cluster
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  # sync privileges that can be granted to a CI system user
  - name: argocd-role
    description: Sync privileges for argocd
    policies:
    - p, proj:argocd-project:argocd-role, applications, sync, argocd-project/argocd-app, allow