apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-projects
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: argocd-project

  # Source of the application manifests
  source:
    repoURL: git@github.com:Gatefail/argocd-monitoring.git
    targetRevision: HEAD
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    manual:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).